language: ruby
rvm:
  - 1.9.3
bundler_args: --without development
script:
  - bundle exec rake
before_install:
  - test_database_setup.sh
  - cp config/database.travis.yml config/database.yml
branches:
  except:
    - master
    - release
notifications:
  email: false