language: ruby
rvm:
  - 1.9.3
bundler_args: --without development
script:
  - bundle exec rake
before_install:
  - mysql -u root -e "CREATE USER 'transition'@'localhost' IDENTIFIED BY 'transition'"
  - mysql -u root -e 'CREATE DATABASE transition_test'
  - mysql -u root -e "GRANT ALL ON transition_test.* TO 'transition'@'localhost'"
  - cp config/database.travis.yml config/database.yml
branches:
  except:
    - master
    - release
notifications:
  email: false